# -*- coding: utf-8 -*-
"""Exwarrdo_AI_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MySVLSWSVc1IhBPRnppl-mHvuWVoE-2
"""

import streamlit as st
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# -------- SAFE OPENCV IMPORT --------
try:
    import cv2
    CV2_AVAILABLE = True
except ImportError:
    cv2 = None
    CV2_AVAILABLE = False

# -------- PAGE CONFIG --------
st.set_page_config(
    page_title="Exwardo | AI Furniture Diagnostics",
    layout="centered"
)

# -------- FUNCTIONS --------
def compute_diagnostics(image_rgb, age):
    """
    Explainable AI diagnostics for furniture health
    Uses classical CV when OpenCV is available,
    otherwise falls back to safe heuristic scoring.
    """

    # ---------- FALLBACK MODE ----------
    if not CV2_AVAILABLE:
        score = max(60, 100 - age * 5)
        return {
            "health_score": score,
            "edge_density": 0.0,
            "texture_variance": 0.0,
            "luminance": 0.0,
            "edges": np.zeros((100, 100))
        }

    # ---------- CV MODE ----------
    image_bgr = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2BGR)
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

    # 1️⃣ Structural integrity proxy — edge density
    edges = cv2.Canny(gray, 50, 150)
    edge_density = np.sum(edges > 0) / edges.size

    # 2️⃣ Surface fatigue proxy — texture variance
    texture_variance = np.var(gray)

    # 3️⃣ Moisture / aging proxy — LAB luminance drift
    lab = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2LAB)
    luminance = np.mean(lab[:, :, 0])

    # ---------- INTERPRETABLE SCORING ----------
    score = 100
    score -= age * 6
    score -= edge_density * 140
    score -= texture_variance / 130
    score -= abs(luminance - 135) / 2

    score = max(25, int(score))

    return {
        "health_score": score,
        "edge_density": edge_density,
        "texture_variance": texture_variance,
        "luminance": luminance,
        "edges": edges
    }

# -------- HEADER --------
st.title("🪑 Exwardo")
st.subheader("Explainable AI for Furniture Asset Wellness")

st.markdown("""
Exwardo detects **invisible furniture decay** using explainable computer vision—
making furniture a **managed, health-tracked asset** instead of a disposable expense.
""")

st.divider()

# -------- AI EXPLANATION --------
st.markdown("""
### 🔍 What the AI Detects

| Decay Type | Signal | Why It Matters |
|-----------|-------|----------------|
| Structural shift | Edge density | Joint gaps, warping |
| Surface fatigue | Texture variance | Cracks, swelling |
| Moisture exposure | Color drift (LAB) | Early rot, stress |

**Pilot principle:** Explainable > Black-box
""")

if not CV2_AVAILABLE:
    st.warning("⚠️ OpenCV not loaded. Running in safe fallback mode (demo scoring).")

st.divider()

# -------- INPUT --------
st.subheader("📸 Upload Furniture Image")

asset_name = st.text_input("Furniture Name", "Wooden Bed")
material = st.selectbox(
    "Material",
    ["Solid Wood", "Engineered Wood", "Metal", "Mixed"]
)
age = st.slider("Furniture Age (Years)", 0, 10, 3)

uploaded_file = st.file_uploader(
    "Upload latest furniture photo",
    type=["jpg", "jpeg", "png"]
)

# -------- PROCESSING --------
if uploaded_file:
    image = Image.open(uploaded_file).convert("RGB")
    image_np = np.array(image)

    st.image(image, caption="Uploaded Asset Image", use_column_width=True)

    results = compute_diagnostics(image_np, age)

    st.divider()
    st.subheader("🧠 AI Diagnostic Results")

    st.metric(
        "Furniture Health Score",
        f"{results['health_score']} / 100"
    )

    if results["health_score"] > 75:
        st.success("Status: Healthy — No action required")
    elif results["health_score"] > 50:
        st.warning("Status: Monitor — Preventive maintenance advised")
    else:
        st.error("Status: Attention Required — Repair or redesign needed")

    # -------- VISUAL EXPLANATION --------
    st.divider()
    st.subheader("📊 Diagnostic Signals")

    col1, col2 = st.columns(2)

    with col1:
        st.write("**Structural Edge Detection**")
        fig, ax = plt.subplots()
        ax.imshow(results["edges"], cmap="gray")
        ax.axis("off")
        st.pyplot(fig)

    with col2:
        st.write("**Numerical Indicators**")
        st.write(f"- Edge Density: `{results['edge_density']:.4f}`")
        st.write(f"- Texture Variance: `{results['texture_variance']:.2f}`")
        st.write(f"- Luminance (LAB): `{results['luminance']:.2f}`")

    st.caption(
        "Health score is computed using weighted, interpretable rules "
        "to ensure transparency and regulatory compatibility."
    )

# -------- MODEL ROADMAP --------
st.divider()
st.subheader("🚀 Model Evolution Roadmap")

st.markdown("""
**Phase 1 (Pilot – Current)**
• Classical computer vision
• Explainable rules & scoring
• Lightweight & auditable

**Phase 2 (Post-Pilot)**
• CNN fine-tuned on labeled furniture damage
• Siamese networks for before–after comparison
• Confidence-weighted predictions
""")

# -------- FOOTER --------
st.divider()
st.caption("Exwardo | PropTech × Circular Economy | Explainable AI Pilot MVP")