# -*- coding: utf-8 -*-
"""Exwarrdo_AI_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MySVLSWSVc1IhBPRnppl-mHvuWVoE-2
"""

import streamlit as st
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# ---------------- CONFIG ----------------
st.set_page_config(
    page_title="Exwardo | AI Furniture Diagnostics",
    layout="centered"
)

# ---------------- FUNCTIONS ----------------

def compute_diagnostics(image_bgr, age):
    """
    Explainable computer vision diagnostics
    """

    # Convert to grayscale
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

    # 1. Structural integrity proxy (edge density)
    edges = cv2.Canny(gray, 50, 150)
    edge_density = np.sum(edges > 0) / edges.size

    # 2. Surface fatigue proxy (texture variance)
    texture_variance = np.var(gray)

    # 3. Moisture / aging proxy (color drift in LAB)
    lab = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2LAB)
    luminance = np.mean(lab[:, :, 0])

    # ---- Interpretable scoring ----
    score = 100
    score -= age * 6
    score -= edge_density * 140
    score -= texture_variance / 130
    score -= abs(luminance - 135) / 2

    score = max(25, int(score))

    return {
        "health_score": score,
        "edge_density": edge_density,
        "texture_variance": texture_variance,
        "luminance": luminance,
        "edges": edges
    }

# ---------------- HEADER ----------------
st.title("🪑 Exwardo")
st.subheader("Explainable AI for Furniture Asset Wellness")

st.markdown("""
Exwardo uses **computer vision–based diagnostics** to detect *invisible decay* in furniture
before it becomes structurally or financially expensive.
""")

st.divider()

# ---------------- EXPLANATION ----------------
st.markdown("""
### 🔍 What the AI Detects

| Decay Type | Signal Used | Why It Matters |
|-----------|------------|----------------|
| Structural shift | Edge density & alignment | Indicates joint gaps, warping |
| Surface fatigue | Texture variance | Captures cracks, peeling, swelling |
| Moisture exposure | Color drift (LAB space) | Early sign of rot or material stress |

> **Pilot principle:** Explainable > Black-box
> This model is intentionally interpretable and auditable.
""")

st.divider()

# ---------------- INPUT ----------------
st.subheader("📸 Upload Furniture Image")

asset_name = st.text_input("Furniture Name", "Wooden Bed")
material = st.selectbox("Material", ["Solid Wood", "Engineered Wood", "Metal", "Mixed"])
age = st.slider("Furniture Age (Years)", 0, 10, 3)

uploaded_file = st.file_uploader(
    "Upload latest furniture photo",
    type=["jpg", "jpeg", "png"]
)

# ---------------- PROCESSING ----------------
if uploaded_file:
    image = Image.open(uploaded_file).convert("RGB")
    image_np = np.array(image)
    image_bgr = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)

    st.image(image, caption="Uploaded Asset Image", use_column_width=True)

    results = compute_diagnostics(image_bgr, age)

    st.divider()
    st.subheader("🧠 AI Diagnostic Results")

    st.metric(
        label="Furniture Health Score",
        value=f"{results['health_score']} / 100"
    )

    # Status interpretation
    if results["health_score"] > 75:
        st.success("Status: Healthy — No action required")
    elif results["health_score"] > 50:
        st.warning("Status: Monitor — Preventive maintenance advised")
    else:
        st.error("Status: Attention Required — Repair or redesign needed")

    # ---------------- VISUAL EXPLANATIONS ----------------
    st.divider()
    st.subheader("📊 Diagnostic Signals (Explainable)")

    col1, col2 = st.columns(2)

    with col1:
        st.write("**Structural Edge Detection**")
        fig, ax = plt.subplots()
        ax.imshow(results["edges"], cmap="gray")
        ax.axis("off")
        st.pyplot(fig)

    with col2:
        st.write("**Numerical Indicators**")
        st.write(f"- Edge Density: `{results['edge_density']:.4f}`")
        st.write(f"- Texture Variance: `{results['texture_variance']:.2f}`")
        st.write(f"- Luminance (LAB): `{results['luminance']:.2f}`")

    st.caption("""
    These indicators are combined using weighted, rule-based logic
    to ensure transparency and regulatory compatibility.
    """)

# ---------------- MODEL ROADMAP ----------------
st.divider()
st.subheader("🚀 Model Evolution Roadmap")

st.markdown("""
**Phase 1 (Pilot – Current)**
- Classical Computer Vision (OpenCV)
- Edge detection, texture statistics, color drift
- Rule-based + linear scoring
- Fully explainable

**Phase 2 (Post-Pilot)**
- CNN fine-tuned on labeled furniture damage
- Siamese networks for before–after comparison
- Confidence-weighted predictions
""")

# ---------------- FOOTER ----------------
st.divider()
st.caption(
    "Exwardo | PropTech × Circular Economy | Explainable AI Pilot MVP"
)